AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LF1:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      CodeUri: s3://sam-templates-niknar/fd58ad41cf0e3e9123e04e88fa851610
      Handler: image_indexing.lambda_handler
      Policies:
      - AWSLambdaExecute
      - CloudWatchLogsFullAccess
      - AmazonRekognitionFullAccess
      - AmazonVPCFullAccess
      Events:
        UploadPhotoEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: B2
            Events: s3:ObjectCreated:*
  B2:
    Type: AWS::S3::Bucket
