AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:  
  LF1:
    Type: AWS::Serverless::Function
    Properties: 
      Runtime: nodejs10.x
      CodeUri: ./lambda-functions
      Handler: image_indexing.handler
      Policies: 
        - AWSLambdaExecute
        - CloudWatchLogsFullAccess
        - AmazonRekognitionFullAccess
        - AmazonVPCFullAccess
      Events:
        UploadPhotoEvent:
          Type: S3
          Properties:
            Bucket: !Ref B2
            Events: s3:ObjectCreated:*
  B2:
    Type: AWS::S3::Bucket
  # Sample for Elasticsearch, to be changed
  # ElasticSearchInstance:
  #   Type: AWS::Elasticsearch::Domain
  #   Properties:
  #     DomainName: "photosearch"
  #     ElasticsearchClusterConfig:
  #       DedicatedMasterEnabled: "false"
  #       InstanceCount: "1"
  #       ZoneAwarenessEnabled: "false"
  #       InstanceType: "t2.small.elasticsearch"
  #     EBSOptions:
  #       EBSEnabled: true
  #       Iops: 0
  #       VolumeSize: 20
  #       VolumeType: "gp2"
  #     SnapshotOptions:
  #       AutomatedSnapshotStartHour: "0"                  